name: Gitee repos mirror periodic job
on:
  # 取消 push 的注释后，向本仓库推送代码即可开始 Gitee 同步
  # push:
  schedule:
    # 每月1号执行一次
    - cron: "0 0 1 * *"
  # 可以在 GitHub 的 Action 页面手动触发工作流
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          # 必选，需要同步的Github用户（源）
          src: github/DesistDaydream
          # 必选，需要同步到的Gitee的用户（目的）
          dst: gitee/DesistDaydream
          # 必选，Gitee公钥对应的私钥，https://gitee.com/profile/sshkeys
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          # 必选，Gitee对应的用于创建仓库的token，https://gitee.com/profile/personal_access_tokens
          dst_token: ${{ secrets.GITEE_TOKEN }}
          # 使用 git push -f 强制覆盖目标仓库
          force_update: true
          # 还有黑、白名单，静态名单机制，可以用于更新某些指定库
          # static_list: repo_name
          black_list: "v2ray,eHualu,alist"
          # white_list: 'repo_name,repo_name2'
          # 强制更新 Gitee 仓库
