name: Gitee repos mirror periodic job
on:
  # 取消 push 的注释后，向本仓库推送代码即可开始 Gitee 同步
  push:
  schedule:
  # 每天北京时间9点跑
  - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache phpdragon src repos
      # 引用发行版的主要版本
      uses: actions/cache@v1
      with:
        path: /home/runner/work/phpdragon/phpdragon-cache
        key: ${{ runner.os }}-phpdragon-repos-cache
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        # 必选，需要同步的Github用户（源）
        src: github/DesistDaydream
        # 必选，需要同步到的Gitee的用户（目的）
        dst: gitee/DesistDaydream
        # 必选，Gitee公钥对应的私钥，https://gitee.com/profile/sshkeys
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        # 必选，Gitee对应的用于创建仓库的token，https://gitee.com/profile/personal_access_tokens
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        # 指定目录cache
        # cache_path: /root/github/workspace/cache
        # 还有黑、白名单，静态名单机制，可以用于更新某些指定库
        # static_list: repo_name
        black_list: 'v2ray,eHualu'
        # white_list: 'repo_name,repo_name2'